In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_excel('01 Train Data.xlsx')

In [3]:
df

First Name           Email ID  Quantity  Price Tier  \
0        ANIKET     aniket@xyz.com         1         NaN   
1     Dhanshree  dhanshree@xyz.com         1         NaN   
2        Dhiraj     dhiraj@xyz.com         1         NaN   
3         Pooja      pooja@xyz.com         1         NaN   
4        Aayush     aayush@xyz.com         1         NaN   
...         ...                ...       ...         ...   
4889   Saif ali    saifali@xyz.com         1         NaN   
4890    Lankesh    lankesh@xyz.com         1         NaN   
4891     Sanjay     sanjay@xyz.com         1         NaN   
4892   Sushmita   sushmita@xyz.com         1         NaN   
4893      Vipul      vipul@xyz.com         1         NaN   

                            Ticket Type    Attendee #  Group  Order Type  \
0                Art of Resume Building  2.213855e+09    NaN  Free Order   
1                Art of Resume Building  2.213859e+09    NaN  Free Order   
2                Art of Resume Building  2.213862e+09    NaN  Free Order   
3                Art of Resume Building  2.213988e+09    NaN  Free Order   
4                Art of Resume Building  2.214567e+09    NaN  Free Order   
...                                 ...           ...    ...         ...   
4889  Data Visualization using Power BI  1.949319e+09    NaN  Free Order   
4890  Data Visualization using Power BI  1.949328e+09    NaN  Free Order   
4891  Data Visualization using Power BI  1.949328e+09    NaN  Free Order   
4892  Data Visualization using Power BI  1.949330e+09    NaN  Free Order   
4893  Data Visualization using Power BI  1.949332e+09    NaN  Free Order   

     Currency  Total Paid  ...  Attendee Status  \
0         USD           0  ...        Attending   
1         USD           0  ...        Attending   
2         USD           0  ...        Attending   
3         USD           0  ...        Attending   
4         USD           0  ...        Attending   
...       ...         ...  ...              ...   
4889      USD           0  ...        Attending   
4890      USD           0  ...        Attending   
4891      USD           0  ...        Attending   
4892      USD           0  ...        Attending   
4893      USD           0  ...        Attending   

                                           College Name  \
0     D Y PATIL INSTITUTE OF MCA AND MANAGEMENT AKUR...   
1                      AP SHAH INSTITUTE OF TECHNOLOGY    
2          Don Bosco College of Engineering Fatorda Goa   
3              Pillai College of Engineering New Panvel   
4                                  St Xavier's College    
...                                                 ...   
4889                 mit academy of engineering ,alandi   
4890                 a. c. patil college of engineering   
4891                                    wilson college    
4892     ld college of engineering, ahmedabad, gujarat    
4893  dkte society's textile and engineering institu...   

           How did you come to know about this event?  \
0                                               Email   
1                                              Others   
2                                               Email   
3                                               Email   
4     Instagram | LinkedIn | Cloud Counselage Website   
...                                               ...   
4889                                              NaN   
4890                                              NaN   
4891                                              NaN   
4892                                              NaN   
4893                                              NaN   

     Specify in "Others" (how did you come to know about this event)  \
0                                                   NaN                
1                                               College                
2                                                   NaN                
3                                                   NaN                
4   

In [4]:
dataset=df.iloc[:, 19:]

In [5]:
dataset

CGPA  Speaking Skills  ML Knowledge Placement Status
0      6.7                2             5           Placed
1      8.2                3             2       Not placed
2      6.5                4             3       Not placed
3      8.7                2             5       Not placed
4      9.1                3             5           Placed
...    ...              ...           ...              ...
4889   9.0                3             2              NaN
4890   7.2                4             3              NaN
4891   8.5                2             3              NaN
4892   6.5                5             5              NaN
4893   6.6                4             5              NaN

[4894 rows x 4 columns]

In [6]:
placement_df= dataset.iloc[:1098,:]

In [7]:
placement_df

CGPA  Speaking Skills  ML Knowledge Placement Status
0      6.7                2             5           Placed
1      8.2                3             2       Not placed
2      6.5                4             3       Not placed
3      8.7                2             5       Not placed
4      9.1                3             5           Placed
...    ...              ...           ...              ...
1093   9.5                4             4       Not placed
1094   9.2                5             5       Not placed
1095   7.9                4             4           Placed
1096   7.3                2             2       Not placed
1097   7.3                2             2       Not placed

[1098 rows x 4 columns]

In [8]:
yog_df=dataset.iloc[1099:,:]

In [9]:
yog_df

CGPA  Speaking Skills  ML Knowledge Placement Status
1099   9.1                3             3              NaN
1100   6.9                2             2              NaN
1101   8.4                4             4              NaN
1102   6.7                5             5              NaN
1103   9.2                2             2              NaN
...    ...              ...           ...              ...
4889   9.0                3             2              NaN
4890   7.2                4             3              NaN
4891   8.5                2             3              NaN
4892   6.5                5             5              NaN
4893   6.6                4             5              NaN

[3795 rows x 4 columns]

# Placement Prediction

In [10]:
placement_dataset= placement_df.iloc[:,:]

In [11]:
placement_dataset

CGPA  Speaking Skills  ML Knowledge Placement Status
0      6.7                2             5           Placed
1      8.2                3             2       Not placed
2      6.5                4             3       Not placed
3      8.7                2             5       Not placed
4      9.1                3             5           Placed
...    ...              ...           ...              ...
1093   9.5                4             4       Not placed
1094   9.2                5             5       Not placed
1095   7.9                4             4           Placed
1096   7.3                2             2       Not placed
1097   7.3                2             2       Not placed

[1098 rows x 4 columns]

In [12]:
X= placement_dataset.iloc[:,:-1].values

In [13]:
X

array([[6.7, 2. , 5. ],
       [8.2, 3. , 2. ],
       [6.5, 4. , 3. ],
       ...,
       [7.9, 4. , 4. ],
       [7.3, 2. , 2. ],
       [7.3, 2. , 2. ]])

In [14]:
for i in range(0, len(X)):
    X[i][1]=int(X[i][1])
    X[i][2]=int(X[i][2])

In [15]:
X

array([[6.7, 2. , 5. ],
       [8.2, 3. , 2. ],
       [6.5, 4. , 3. ],
       ...,
       [7.9, 4. , 4. ],
       [7.3, 2. , 2. ],
       [7.3, 2. , 2. ]])

In [16]:
y= placement_dataset.iloc[:, -1].values

In [17]:
y

array(['Placed', 'Not placed', 'Not placed', ..., 'Placed', 'Not placed',
       'Not placed'], dtype=object)

In [18]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y= le.fit_transform(y)

In [19]:
y

array([1, 0, 0, ..., 1, 0, 0])

In [20]:
y = y.astype(int)

In [21]:
print(y)

[1 0 0 ... 1 0 0]


In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=0)

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

#### Logistic Regression

In [24]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [25]:
y_pred=classifier.predict(X_test)

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred)
accuracy= accuracy_score(y_test, y_pred)
print(cm)

[[158   0]
 [ 62   0]]


In [27]:
print("Accuracy when using Logistic regression is: "+ str(accuracy))

Accuracy when using Logistic regression is: 0.7181818181818181


#### Naïve Bayes

In [28]:
from sklearn.naive_bayes import GaussianNB
classifier= GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [29]:
y_pred= classifier.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred)
print(cm)
accuracy= accuracy_score(y_test, y_pred)

[[158   0]
 [ 62   0]]


In [31]:
print("Accuracy when using Naive Bayes Classification is: " +str(accuracy))

Accuracy when using Naive Bayes Classification is: 0.7181818181818181


#### Decision Tree Classifier

In [32]:
from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier(criterion='gini', random_state=42)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [33]:
y_pred = classifier.predict(X_test)

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[146  12]
 [ 54   8]]


In [35]:
accuracy=accuracy_score(y_test, y_pred)

In [36]:
print("Accuracy when using Decision Tree Classification is: " +str(accuracy))

Accuracy when using Decision Tree Classification is: 0.7


#### Random Forest Classifier

In [37]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [38]:
y_pred = classifier.predict(X_test)

In [39]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy=accuracy_score(y_test, y_pred)

[[141  17]
 [ 56   6]]


In [40]:
print("Accuracy when using Random Forest Classification is: " +str(accuracy))

Accuracy when using Random Forest Classification is: 0.6681818181818182


#### Artificial Neural Network

In [41]:
import tensorflow as tf

In [42]:
ann= tf.keras.models.Sequential()


In [43]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [44]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [45]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [46]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

In [47]:
ann.fit(X_train, y_train, batch_size= 32, epochs=200)

Epoch 1/200
28/28 [==============================] - 1s 2ms/step - loss: 0.7569 - accuracy: 0.3485
Epoch 2/200
28/28 [==============================] - 0s 2ms/step - loss: 0.7280 - accuracy: 0.4089
Epoch 3/200
28/28 [==============================] - 0s 2ms/step - loss: 0.7076 - accuracy: 0.4761
Epoch 4/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6935 - accuracy: 0.5535
Epoch 5/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6828 - accuracy: 0.5854
Epoch 6/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6738 - accuracy: 0.6401
Epoch 7/200
28/28 [==============================] - 0s 3ms/step - loss: 0.6666 - accuracy: 0.6538
Epoch 8/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6602 - accuracy: 0.6538
Epoch 9/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6555 - accuracy: 0.6538
Epoch 10/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6514 - accuracy: 0.6538
Epoch 11/

28/28 [==============================] - 0s 2ms/step - loss: 0.6398 - accuracy: 0.6526
Epoch 84/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6396 - accuracy: 0.6526
Epoch 85/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6395 - accuracy: 0.6526
Epoch 86/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6397 - accuracy: 0.6526
Epoch 87/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6395 - accuracy: 0.6538
Epoch 88/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6393 - accuracy: 0.6538
Epoch 89/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6393 - accuracy: 0.6526
Epoch 90/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6394 - accuracy: 0.6526
Epoch 91/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6396 - accuracy: 0.6526
Epoch 92/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6393 - accuracy: 0.6526
Epoch 93/200


28/28 [==============================] - 0s 2ms/step - loss: 0.6363 - accuracy: 0.6526
Epoch 165/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6363 - accuracy: 0.6526
Epoch 166/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6365 - accuracy: 0.6538
Epoch 167/200
28/28 [==============================] - 0s 3ms/step - loss: 0.6363 - accuracy: 0.6526
Epoch 168/200
28/28 [==============================] - 0s 3ms/step - loss: 0.6360 - accuracy: 0.6526
Epoch 169/200
28/28 [==============================] - 0s 3ms/step - loss: 0.6360 - accuracy: 0.6526
Epoch 170/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6362 - accuracy: 0.6526
Epoch 171/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6360 - accuracy: 0.6538
Epoch 172/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6359 - accuracy: 0.6526
Epoch 173/200
28/28 [==============================] - 0s 2ms/step - loss: 0.6359 - accuracy: 0.6526
Epoc

In [48]:
y_pred= ann.predict(X_test)
y_pred= y_pred>0.5

7/7 [==============================] - 0s 2ms/step


In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, y_pred)
print(cm)
accuracy= accuracy_score(y_test, y_pred)

[[157   1]
 [ 59   3]]


In [50]:
print("Accuracy when using Artificial Neural Network is: " +str(accuracy))

Accuracy when using Artificial Neural Network is: 0.7272727272727273


# Year of Graduation Prediction

In [51]:
yog_dataset=df.iloc[:, 18:]

In [52]:
yog_dataset

Year of Graduation  CGPA  Speaking Skills  ML Knowledge Placement Status
0                   NaN   6.7                2             5           Placed
1                   NaN   8.2                3             2       Not placed
2                   NaN   6.5                4             3       Not placed
3                   NaN   8.7                2             5       Not placed
4                   NaN   9.1                3             5           Placed
...                 ...   ...              ...           ...              ...
4889               2021   9.0                3             2              NaN
4890               2021   7.2                4             3              NaN
4891               2021   8.5                2             3              NaN
4892               2021   6.5                5             5              NaN
4893               2021   6.6                4             5              NaN

[4894 rows x 5 columns]

In [53]:
yog=yog_dataset.iloc[1099:,:-1]

In [54]:
yog

Year of Graduation  CGPA  Speaking Skills  ML Knowledge
1099                NaN   9.1                3             3
1100                NaN   6.9                2             2
1101                NaN   8.4                4             4
1102                NaN   6.7                5             5
1103                NaN   9.2                2             2
...                 ...   ...              ...           ...
4889               2021   9.0                3             2
4890               2021   7.2                4             3
4891               2021   8.5                2             3
4892               2021   6.5                5             5
4893               2021   6.6                4             5

[3795 rows x 4 columns]

In [55]:
yog=yog.dropna()

In [56]:
yog_df=yog.iloc[:,:]

In [57]:
yog_df

Year of Graduation  CGPA  Speaking Skills  ML Knowledge
2318        Second year   6.5                3             3
2319        Second year   8.7                3             3
2320               2019   9.1                1             1
2321               2023   8.9                3             3
2322               2023   7.4                3             3
...                 ...   ...              ...           ...
4889               2021   9.0                3             2
4890               2021   7.2                4             3
4891               2021   8.5                2             3
4892               2021   6.5                5             5
4893               2021   6.6                4             5

[1032 rows x 4 columns]

In [58]:
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values= np.nan, strategy='median')

In [59]:
X= yog.iloc[:, 1:].values
y= yog.iloc[: ,0].values

In [60]:
print(X)

[[6.5 3.  3. ]
 [8.7 3.  3. ]
 [9.1 1.  1. ]
 ...
 [8.5 2.  3. ]
 [6.5 5.  5. ]
 [6.6 4.  5. ]]


In [61]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train= sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [62]:
print(y)

['Second year' 'Second year' '2019' ... '2021' '2021' '2021']


In [63]:
year_mapping = {
    'Second year': 2026,
    'Third year': 2025,
    'Final year': 2024,
    'Fourth year': 2024,
    'Bachelor of Engineering': 2027,
}
for i in range(len(y)):
    if y[i] in year_mapping:
        y[i] = year_mapping[y[i]]
    elif not isinstance(y[i], int):
        y[i] = 2023

In [64]:
print(y)

[2026 2026 2023 ... 2023 2023 2023]


In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=0)

#### Simple Linear Regression

In [66]:
from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [67]:
y_pred= regressor.predict(X_test)
y_pred = y_pred.astype(int)

In [68]:
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis=1))

[[2023 2026]
 [2023 2023]
 [2023 2023]
 [2023 2026]
 [2023 2023]
 [2023 2025]
 [2023 2025]
 [2023 2026]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2026]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2026]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2025]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2025]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2025]
 [2023 2023]
 [2023 2026]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2025]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2025]
 [2023 2023]
 [2023 2023]
 [2023 2025]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2026]
 [2023 2023]
 [2023 2026]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2026]
 [2023 2023]
 [2023 2026]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2025]
 [2023 2023]
 [2023 2023]
 [2023 2023]
 [2023 2025]
 [2023 2023]
 [2023 2026]

In [69]:
len(y_train)

825

In [70]:
len(yog)

1032

# Testing and pushing to excel

In [71]:
data = pd.read_excel('02 Test Data.xlsx')

In [72]:
data

First Name            Email ID  Quantity  Price Tier  \
0         Sahil        sahil@xyz.com         1         NaN   
1        Amrita       amrita@xyz.com         1         NaN   
2          Mamta       mamta@xyz.com         1         NaN   
3     Bhagyashri  bhagyashri@xyz.com         1         NaN   
4      Divyanshu   divyanshu@xyz.com         1         NaN   
...          ...                 ...       ...         ...   
3791    Saif ali     saifali@xyz.com         1         NaN   
3792     Lankesh     lankesh@xyz.com         1         NaN   
3793      Sanjay      sanjay@xyz.com         1         NaN   
3794    Sushmita    sushmita@xyz.com         1         NaN   
3795       Vipul       vipul@xyz.com         1         NaN   

                            Ticket Type    Attendee #  Group  Order Type  \
0                       Hello ML and DL  2.293940e+09    NaN  Free Order   
1                       Hello ML and DL  2.293941e+09    NaN  Free Order   
2                       Hello ML and DL  2.293941e+09    NaN  Free Order   
3                       Hello ML and DL  2.293946e+09    NaN  Free Order   
4                       Hello ML and DL  2.293956e+09    NaN  Free Order   
...                                 ...           ...    ...         ...   
3791  Data Visualization using Power BI  1.949319e+09    NaN  Free Order   
3792  Data Visualization using Power BI  1.949328e+09    NaN  Free Order   
3793  Data Visualization using Power BI  1.949328e+09    NaN  Free Order   
3794  Data Visualization using Power BI  1.949330e+09    NaN  Free Order   
3795  Data Visualization using Power BI  1.949332e+09    NaN  Free Order   

     Currency  Total Paid  ...  Attendee Status  \
0         USD           0  ...        Attending   
1         USD           0  ...        Attending   
2         USD           0  ...        Attending   
3         USD           0  ...        Attending   
4         USD           0  ...        Attending   
...       ...         ...  ...              ...   
3791      USD           0  ...        Attending   
3792      USD           0  ...        Attending   
3793      USD           0  ...        Attending   
3794      USD           0  ...        Attending   
3795      USD           0  ...        Attending   

                                           College Name  \
0               symbiosis institute of technology, pune   
1                    mit academy of engineering ,alandi   
2                    a. c. patil college of engineering   
3                                       wilson college    
4        ld college of engineering, ahmedabad, gujarat    
...                                                 ...   
3791                 mit academy of engineering ,alandi   
3792                 a. c. patil college of engineering   
3793                                    wilson college    
3794     ld college of engineering, ahmedabad, gujarat    
3795  dkte society's textile and engineering institu...   

      How did you come to know about this event?  \
0                                       Whatsapp   
1                                       Whatsapp   
2                                       Whatsapp   
3                                         Others   
4                                       Whatsapp   
...                                          ...   
3791                                         NaN   
3792                                         NaN   
3793                                         NaN   
3794                                         NaN   
3795                                         NaN   

     Specify in "Others" (how did you come to know about this event)  \
0                                                   NaN                
1                                                   NaN                
2                                                   NaN                
3                                                   NaN                
4                                        

In [73]:
test_df= data

In [74]:
test_df= test_df.iloc[:, 19:-1].values

In [75]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
test_df= sc.fit_transform(test_df)

In [76]:
y1 = classifier.predict(test_df)
y2= regressor.predict(test_df)

In [77]:
y2

array([2023.77236889, 2023.73250541, 2023.81354751, ..., 2023.69942769,
       2023.78507071, 2023.73052804])

In [78]:
len(y1)

3796

In [79]:
len(data)

3796

In [80]:
results_df = pd.DataFrame(y1)
results_df2 = pd.DataFrame(y2)

In [81]:
data['Placement Status']= results_df
data['Year of Graduation']= results_df2

In [82]:
data

First Name            Email ID  Quantity  Price Tier  \
0         Sahil        sahil@xyz.com         1         NaN   
1        Amrita       amrita@xyz.com         1         NaN   
2          Mamta       mamta@xyz.com         1         NaN   
3     Bhagyashri  bhagyashri@xyz.com         1         NaN   
4      Divyanshu   divyanshu@xyz.com         1         NaN   
...          ...                 ...       ...         ...   
3791    Saif ali     saifali@xyz.com         1         NaN   
3792     Lankesh     lankesh@xyz.com         1         NaN   
3793      Sanjay      sanjay@xyz.com         1         NaN   
3794    Sushmita    sushmita@xyz.com         1         NaN   
3795       Vipul       vipul@xyz.com         1         NaN   

                            Ticket Type    Attendee #  Group  Order Type  \
0                       Hello ML and DL  2.293940e+09    NaN  Free Order   
1                       Hello ML and DL  2.293941e+09    NaN  Free Order   
2                       Hello ML and DL  2.293941e+09    NaN  Free Order   
3                       Hello ML and DL  2.293946e+09    NaN  Free Order   
4                       Hello ML and DL  2.293956e+09    NaN  Free Order   
...                                 ...           ...    ...         ...   
3791  Data Visualization using Power BI  1.949319e+09    NaN  Free Order   
3792  Data Visualization using Power BI  1.949328e+09    NaN  Free Order   
3793  Data Visualization using Power BI  1.949328e+09    NaN  Free Order   
3794  Data Visualization using Power BI  1.949330e+09    NaN  Free Order   
3795  Data Visualization using Power BI  1.949332e+09    NaN  Free Order   

     Currency  Total Paid  ...  Attendee Status  \
0         USD           0  ...        Attending   
1         USD           0  ...        Attending   
2         USD           0  ...        Attending   
3         USD           0  ...        Attending   
4         USD           0  ...        Attending   
...       ...         ...  ...              ...   
3791      USD           0  ...        Attending   
3792      USD           0  ...        Attending   
3793      USD           0  ...        Attending   
3794      USD           0  ...        Attending   
3795      USD           0  ...        Attending   

                                           College Name  \
0               symbiosis institute of technology, pune   
1                    mit academy of engineering ,alandi   
2                    a. c. patil college of engineering   
3                                       wilson college    
4        ld college of engineering, ahmedabad, gujarat    
...                                                 ...   
3791                 mit academy of engineering ,alandi   
3792                 a. c. patil college of engineering   
3793                                    wilson college    
3794     ld college of engineering, ahmedabad, gujarat    
3795  dkte society's textile and engineering institu...   

      How did you come to know about this event?  \
0                                       Whatsapp   
1                                       Whatsapp   
2                                       Whatsapp   
3                                         Others   
4                                       Whatsapp   
...                                          ...   
3791                                         NaN   
3792                                         NaN   
3793                                         NaN   
3794                                         NaN   
3795                                         NaN   

     Specify in "Others" (how did you come to know about this event)  \
0                                                   NaN                
1                                                   NaN                
2                                                   NaN                
3                                                   NaN                
4                                        

In [83]:
data['Placement Status'] = data['Placement Status'].replace(0,'Not Placed')
data['Placement Status'] = data['Placement Status'].replace(1,'Placed')


data['Year of Graduation']= data['Year of Graduation'].round(0) 

In [84]:
print(data['Placement Status'].value_counts())

Not Placed    3060
Placed         736
Name: Placement Status, dtype: int64


In [85]:
print(data['Year of Graduation'].value_counts())

2024.0    3796
Name: Year of Graduation, dtype: int64


# Pushing into excel

In [86]:
excel_file_path= 'Results.xlsx'
data.to_excel(excel_file_path, index= False)